import type { Metadata, Viewport } from 'next'
import { Bricolage_Grotesque, Inter, Orbitron, JetBrains_Mono } from 'next/font/google'
import './globals.css'
import { SpeedInsights } from '@vercel/speed-insights/next'
import LanguageSelector from '@/components/LanguageSelector'
import SettingsSidebar from '@/components/SettingsSidebar'
import GlobalClientComponents from '@/components/GlobalClientComponents'
import { I18nProvider } from '@/components/I18nContext'
import JsonLd, { WEB_APP_SCHEMA, ORG_SCHEMA } from '@/components/JsonLd'

/* ── Font subsetting (#32): latin-only, swap, no fallback shift ─── */
// Weights trimmed to exactly what the design system uses (globals.css comment):
// 400 → body copy, 700 → section titles, 800 → hero-only heads
// Previously loaded 7 weights (200–800); saving ~4 font file requests.
const bricolage = Bricolage_Grotesque({
  subsets: ['latin'],
  weight: ['400', '700', '800'],
  variable: '--font-display',
  display: 'swap',
  adjustFontFallback: false,
})

// Inter Variable: full 100–900 weight axis from a single font file.
// Removes the need for separate static-weight font requests.
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
  adjustFontFallback: false,
})

const orbitron = Orbitron({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-orbitron',
  display: 'swap',
  adjustFontFallback: false,
  // Subset to only the characters used: N E X U S · (saves ~90% of font download)
  // @ts-expect-error — `text` subsetting is valid in Next.js 13.2+ but not yet reflected in these type defs
  text: 'NEXUS·',
})

// JetBrains Mono: 400 + 500 only — used for badges, distances, code labels.
// 600 weight removed, saving one font file.
const mono = JetBrains_Mono({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--font-mono',
  display: 'swap',
  adjustFontFallback: false,
})

export const metadata: Metadata = {
  title: 'NEXUS — Free Healthcare, Found in Seconds',
  description:
    'NEXUS finds free clinics, sliding-scale care, and hidden programs for the 30 million uninsured Americans who deserve better.',
  keywords: ['free healthcare', 'free clinic', 'uninsured', 'healthcare access', 'NEXUS'],
  manifest: '/manifest.json',
  openGraph: {
    title: 'NEXUS — Free Healthcare, Found in Seconds',
    description: 'Find free clinics, sliding-scale care, and eligibility programs near you. No insurance required.',
    siteName: 'NEXUS',
    type: 'website',
    // D9: dynamic OG image via @vercel/og edge function
    images: [{ url: `${process.env.NEXT_PUBLIC_APP_URL ?? 'https://nexus-healthcare.vercel.app'}/api/og`, width: 1200, height: 630, alt: 'NEXUS — Free Healthcare, Found in Seconds' }],
  },
  twitter: {
    card: 'summary_large_image',
    site: '@nexushealth',
    creator: '@nexushealth',
    title: 'NEXUS — Free Healthcare, Found in Seconds',
    description: 'Find free clinics, sliding-scale care, and eligibility programs near you. No insurance required.',
    images: [`${process.env.NEXT_PUBLIC_APP_URL ?? 'https://nexus-healthcare.vercel.app'}/api/og`],
  },
}

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: dark)',  color: '#040408' },
    { media: '(prefers-color-scheme: light)', color: '#040408' },
  ],
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${bricolage.variable} ${inter.variable} ${orbitron.variable} ${mono.variable}`}
    >
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5" />

        {/* P7 — Preconnect + preload for Google Fonts CDN */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="manifest" href="/manifest.json" />
        {/* Apple touch icon is auto-generated by app/apple-icon.tsx */}
        {/* S5 — hreflang for multi-language support (48 languages via i18n) */}
        <link rel="alternate" hrefLang="x-default" href="https://nexus.health/" />
        <link rel="alternate" hrefLang="en" href="https://nexus.health/" />
        <link rel="alternate" hrefLang="es" href="https://nexus.health/?lang=es" />
        <link rel="alternate" hrefLang="zh" href="https://nexus.health/?lang=zh" />
        <link rel="alternate" hrefLang="fr" href="https://nexus.health/?lang=fr" />
        <link rel="alternate" hrefLang="ar" href="https://nexus.health/?lang=ar" />
        <link rel="alternate" hrefLang="pt" href="https://nexus.health/?lang=pt" />
        <link rel="alternate" hrefLang="hi" href="https://nexus.health/?lang=hi" />
        <link rel="alternate" hrefLang="ru" href="https://nexus.health/?lang=ru" />
        <link rel="alternate" hrefLang="ko" href="https://nexus.health/?lang=ko" />
        <link rel="alternate" hrefLang="vi" href="https://nexus.health/?lang=vi" />
        {/* 5.9 — Structured Data */}
        <JsonLd schema={WEB_APP_SCHEMA} id="schema-webapp" />
        <JsonLd schema={ORG_SCHEMA} id="schema-org" />
      </head>
      <body suppressHydrationWarning>
        <I18nProvider>
          {children}
          <GlobalClientComponents />
          <LanguageSelector />
          <SettingsSidebar />
          <SpeedInsights />
        </I18nProvider>
      </body>
    </html>
  )
}
